name: Continuous Integration Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 17]
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"

      - name: Build and test with Coverage
        run: |
          mvn clean install -Pcoverage
          mvn jacoco:report

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: Jacoco Report
          path: target/site/jacoco/
