name: Send zip
on:
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log recent commit
        run: git log -1

      - name: Files in the project
        run: ls -R
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Zip code coverage report directory
        run: zip -r coverageReport.zip target/site

      - name: Upload code coverage report to google drive
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCA_SA_KEY }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          filename: "coverageReport.zip"
          overwrite: "true"
