name: Pull Request Management

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  pr-management:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.16.3  # Update to the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Correctly placed as an environment variable

      - name: Add labels
        uses: actions/labeler@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration-path: .github/labeler/labeler.yml
