name: Pull Request Management

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  pr-management:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessary for actions/checkout to clone the repository
      pull-requests: write # Necessary for merging pull requests and managing pull request details

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Optionally, fetch all history if needed for complex workflows
      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.14.3
        with:
          mergeMethod: merge # The method to use when merging the pull request into the base branch
          githubToken: ${{ secrets.SOFTWARE_QUALITY }}
      - name: Add labels
        uses: actions/labeler@v3
        with:
          configuration-path: .github/labeler.yml # Path to the label configuration file
          githubToken: ${{ secrets.SOFTWARE_QUALITY }} # Ensure environment variable is correctly set
